### ISSUE TITLE
CPM-2-Pretrain数据处理与读取问题

### ISSUE THREAD

**Issue by RoyZhanyi** [TsinghuaAI/CPM-2#10]
您好～ 我在尝试跑CPM-2-Pretrain代码时发现以下问题：

在“src-->data-->dataset_utils.py”中compile_helper()与deepspeed相比 发现缺失以下代码
ret = subprocess.run(['make', '-C', path])
如若不加此行代码会出现 import helper导入不成功，如果加上上述代码会出现2的问题。
请问该行代码是否需要加上？

当我加入ret = subprocess.run(['make', '-C', path]) 进行预训练会出现数组越界问题
IndexError：index 53004 is out of bounds for axis 0 with size 62
问题出现在“src-->data-->enc_dec_dataset.py” line228. 我检查了一下似乎出现在了offset=tmp_target_offset[2 * x]这个上面。
不知道问题出在哪里。

很抱歉不能把原版错误粘贴出来。。问题困扰了我两天，还望作者能帮忙解答一下此处问题！万分感谢❤️❤️❤️

**Comment by t1101675** [comment]
#9
