### ISSUE TITLE
If training, what is the minimum computer configuration

### ISSUE THREAD

**Issue by zhanghongyong123456** [TsinghuaAI/CPM-2#11]

**Comment by t1101675** [comment]
In our experience, our model can be trained on 2 * 8 * 32G V100, with small batch size. However, considering the model performance and the training efficiency, we recommend using at least 20 * 8 * 32G V100.

**Comment by XiaoqingNLP** [comment]
@t1101675 @zzy14  If I use this setting, approximately how long will it take? How long did it take to train our CPM Chinese model?

**Comment by t1101675** [comment]
It took us about 30 days to train the model from scratch.

**Comment by XiaoqingNLP** [comment]
@t1101675 请教一个我发现的比较奇怪的现象（以下batch size 均指pretrain_enc_dec.sh中的batch size）：
1. 一台机器的能支持的batch size 最大只能是x，但是我用两台机器能支持的batch size变大了5倍；
2. 然后我验证了代码，batch size是指的每个data parallel 的batch size；
这是为什么呢？其余设置相同，没想明白为什么，然后也检查了，是我弄错了吗？

**Comment by t1101675** [comment]
这是因为代码用了 zero-1 优化，它将优化器占用的显存摊到了数据并行的进程上，因此用的卡越多，单卡的显存占用越小，单卡开的 batch size 也越大

**Comment by XiaoqingNLP** [comment]
@t1101675 方便透露一下你们的吞吐情况吗？例如基本设置下的1台机器和2台机器的对比？能透露更多当然好了

**Comment by t1101675** [comment]
实在抱歉我们没有测过这个数值

**Comment by XiaoqingNLP** [comment]
@t1101675 那你们多台机器的能给吗？参考一下
