### ISSUE TITLE
Deepspeed Zero3?

### ISSUE THREAD

**Issue by k15201363625** [TsinghuaAI/CPM-2#12]
Zero-stage-3 error:RuntimeError: output with shape [1] doesn't match the broadcast shape [26240, 512]

**Comment by t1101675** [comment]
We used Zero-stage-1 to train our model. It's not clear whether our code supports zero-3. We will try this later. Thanks!

**Comment by k15201363625** [comment]
Thanks very much!

**Comment by k15201363625** [comment]
I made the following changes in `enc_dec_modeling.py`：
**__init__**
```
# self.lm_head = mpu.VocabParallelEmbedding(config.vocab_size, config.d_model, init_method=init_method) # origin
self.lm_head = nn.Linear(config.d_model,config.vocab_size) # solution 1
```
**forward()**
```
# logits_parallel = F.linear(last_hidden_state_parallel, self.lm_head.weight) # origin
logits_parallel = self.lm_head(last_hidden_state_parallel) # solution 1
logits_parallel = F.linear(last_hidden_state_parallel,self.encoder.word_embeds.weight) # solution 2
```
conference: https://github.com/PyTorchLightning/pytorch-lightning/issues/8508
But I don't understand why this works.

**Comment by t1101675** [comment]
Does the model produce normal loss? In the original implementation, the vocab is distributed on multiple devices. That's why we use `mpu.VocabParallelEmbedding` in which we handle data across different devices.

**Comment by k15201363625** [comment]
Thanks.
For TP on lm_head layer, `nn.Linear` can not be accepted.
should be:    
```
self.lm_head = mpu.VocabParallelEmbedding(config.vocab_size, config.d_model, init_method=init_method)
or
self.lm_head = mpu.ColumnParallelLinear(config.d_model,config.vocab_size,gather_output=False,bias=False,init_method=init_method)

```
Furthermore, I find that works on zero stage 3, when we move loss computation in model forward function.
(reference:DeepspeedExample)
