### ISSUE TITLE
Model checkpoint convert

### ISSUE THREAD

**Issue by k15201363625** [TsinghuaAI/CPM-2#13]
How to complete the transformation：
Deepspeed_ckpt to  mp_model(tensor parallel) to single_model(single ckpt) with zero-1/2 and mp(tensor parallel) training.
Furthermore,Deepspeed version should be?
thanks very much.

**Comment by t1101675** [comment]
You can refer to https://github.com/TsinghuaAI/CPM-1-Generate/blob/main/change_mp.py for the transformation.
The deepspeed version is `0.3.9+59e4dbb`. You can directly use our docker to run the model.

**Comment by k15201363625** [comment]
Thank you very much!
