### ISSUE TITLE
专家网络参数应该broadcast么

### ISSUE THREAD

**Issue by icodingc** [TsinghuaAI/CPM-2#14]
https://github.com/TsinghuaAI/CPM-2-Pretrain/blob/moe/src/model/distributed.py#L33
![image](https://user-images.githubusercontent.com/5784259/129469447-cbea5e29-2e01-4d3c-84dd-f58610c828fe.png)
专家网络是不是不应该broadcast呢。

**Comment by zzy14** [comment]
训练专家网络的时候我们是用对应的实心模型的ffn层来初始化，一开始每个专家网络的参数是一样的，随着训练参数会有变化，专家网络的梯度是不做broadcast的，每个网路都有一套自己的。

**Comment by icodingc** [comment]
这样多谢。

**Comment by XiaoqingNLP** [comment]
@zzy14  @t1101675 @icodingc 这个部分初始化的代码是不是没有开源？

> 训练专家网络的时候我们是用对应的实心模型的ffn层来初始化，一开始每个专家网络的参数是一样的，随着训练参数会有变化，专家网络的梯度是不做broadcast的，每个网路都有一套自己的。

**Comment by zzy14** [comment]
@Qnlp [这里](https://github.com/TsinghuaAI/CPM-2-Pretrain/blob/moe/init_ckpt.py)是初始化的代码，逻辑比较简单，就是增加一个expert的网络，其余的参数不变。

**Comment by XiaoqingNLP** [comment]
@zzy14 @t1101675 @icodingc 在CPM2 论文中显示MoE stage 需要将双语阶段的模型重复几次，以初始化一个MoE模型。
有以下问题想请教：
1. 那如果一开始每个专家网络的参数是一样的，需要重复几次是什么用途？
2. 如果先broadcast，再加载模型初始化，那按道理broadcast没有意义吧？
3. 加载moe进行继续预训练，训练损失会重新从一个较大值开始下降，这很奇怪？
