### ISSUE TITLE
Model parallelism of CPM2-MoE

### ISSUE THREAD

**Issue by MichaelXSChen** [TsinghuaAI/CPM-2#15]
May i know how is the model partitioned in CPM-2 MoE? It seems each rank only takes 1 expert, and each expert is further partitioned (i.e., 256 model partitions in total)?

Thank you for your info.

**Comment by zzy14** [comment]
Hi,

Yes, you are right! There are 32 experts and model parallelism is set to 8 GPUs. Hence, the total number of model partitions is 256.

**Comment by XiaoqingNLP** [comment]
@zzy14 @MichaelXSChen  What confuses me is this parameter setting, shouldn't it be d_ffn (10240) * 32 here？？？https://github.com/TsinghuaAI/CPM-2-Pretrain/blob/a00b3dd70d71a796a1ed2a925ddf7902e0209ab3/src/configs/model/enc_dec_xlarge_config.json#L3
