### ISSUE TITLE
CPM-2-Pretrain-moe的词表问题

### ISSUE THREAD

**Issue by jiayuchennlp** [TsinghuaAI/CPM-2#17]
您好，我在加载moe的模型时候遇到了问题：
RuntimeError: Error(s) in loading state_dict for EncDecModel:
        size mismatch for word_embeds.weight: copying a param with shape torch.Size([6496, 4096]) from checkpoint, the shape in current model is torch.Size([6592, 4096]).
        size mismatch for lm_head.weight: copying a param with shape torch.Size([6496, 4096]) from checkpoint, the shape in current model is torch.Size([6592, 4096]).
        size mismatch for encoder.word_embeds.weight: copying a param with shape torch.Size([6496, 4096]) from checkpoint, the shape in current model is torch.Size([6592, 4096]).
        size mismatch for decoder.word_embeds.weight: copying a param with shape torch.Size([6496, 4096]) from checkpoint, the shape in current model is torch.Size([6592, 4096]).
这里的词表用的是中英文词表：
[https://github.com/TsinghuaAI/CPM-2-Pretrain/blob/moe/bpe_cn_en/vocab.txt](url)

我的疑问是：
这个词表的大小是52736=6592乘以8，为什么加载过程中报错，显示模型文件中的词表大小是6496乘以8？

这个问题非常困扰我，还请作者帮忙解答，万分感谢~~

还有一个小疑问，中英文词表的中文字符最后一行26050行是不是有点问题？（与中文词表的26050行不太一样）
[https://github.com/TsinghuaAI/CPM-2-Pretrain/blob/moe/bpe_cn_en/vocab.txt#L26050](url)

**Comment by zzy14** [comment]
Hi 抱歉，之前放的词表不是最新的，刚刚更新了一下，您试试

**Comment by XiaoqingNLP** [comment]
MOE里面的词表没有更新，用主分支下的词表可行
