### ISSUE TITLE
Link for 《CUGE: A chinese language understanding and generation evaluation benchmark》

### ISSUE THREAD

**Issue by sjy1203** [TsinghuaAI/CPM-2#2]
Great Paper！Could you kindly provide the link for CUGE and CCPR dataset?

**Comment by t1101675** [comment]
The paper of the CUGE benchmark will appear on arxiv in a few days.

**Comment by t1101675** [comment]
The information for CUGE benchmark can refer to http://cuge.baai.ac.cn/.

**Comment by t1101675** [comment]
https://arxiv.org/abs/2112.13610
