### ISSUE TITLE
CPM2模型推理代码

### ISSUE THREAD

**Issue by Bournet** [TsinghuaAI/CPM-2#22]
基于 CPM2 微调了一版模型，想用微调的模型做推理，请问有针对 CPM2 模型的单卡或者多卡的推理代码吗

**Comment by t1101675** [comment]
可以参考 https://github.com/TsinghuaAI/CPM-2-Finetune/issues/30

**Comment by XiaoqingNLP** [comment]
@Bournet 你好，请问你微调的任务以及效果如何？
