### ISSUE TITLE
Dev/Test split for Math23K dataset

### ISSUE THREAD

**Issue by sjy1203** [TsinghuaAI/CPM-2#3]
Dear authors,
How do you split the Math23K dataset for validation and test?

**Comment by t1101675** [comment]
The details of our downstream data will be described in the paper of the CUGE benchmark, which will appear on arxiv in a few days.

**Comment by t1101675** [comment]
The information for CUGE benchmark can refer to http://cuge.baai.ac.cn/.

**Comment by t1101675** [comment]
https://arxiv.org/abs/2112.13610
