### ISSUE TITLE
请问后续会放出sample供使用参考吗？

### ISSUE THREAD

**Issue by NLPIG** [TsinghuaAI/CPM-2#4]
如题，有没有像CMP-Generate提供各个任务具体的使用模板呢？

**Comment by t1101675** [comment]
会的，我们会在 CUGE 数据集论文放出之后一并提供。

**Comment by NLPIG** [comment]
谢谢你们！CPM对我们的启发非常大，相信CPM-2会再次惊艳我们！

gyxbndsthu ***@***.***> 于2021年6月7日周一 下午8:11写道：

**Comment by t1101675** [comment]
CPM-2 的 Fine-tune 代码已经开源，可以参考 [CPM-2-Finetune](https://github.com/TsinghuaAI/CPM-2-Finetune) 仓库。
