### ISSUE TITLE
How do I start and use the docker image?  Is a k80 enough?

### ISSUE THREAD

**Issue by MikeyBeez** [TsinghuaAI/CPM-2#7]

**Comment by MikeyBeez** [comment]
In my excitement, I forgot my manners.  Thank you for posting this model.  I've tried to start this with docker run -it docker.io/gyxthu17/cpm-2:1.0 bash and with docker run -p 8080:8080 gyxthu17/cpm-2:1.0  Neither works for me.  I'd like to run this for question answer, text generation, summarization, inference, etc.

**Comment by t1101675** [comment]
Could you please post the error message? This would be helpful for us to solve the problem.

**Comment by MikeyBeez** [comment]
Thank you for responding.  I don't get an error.  I just don't know what to do with the container.  You probably explain it very well, but I only know a few words of Chinese and no characters.  I don;t see a script directory.  I get this container for the root user:
`root@f524975642fd:/# ls
:     data     etc   lib64  mnt            opt   run   sys  var
bin   dataset  home  logs   model          proc  sbin  tmp  workspace
boot  dev      lib   media  oh-my-tuna.py  root  srv   usr

**Comment by MikeyBeez** [comment]
Can this be run like a chatbot?

**Comment by MikeyBeez** [comment]
I've made some progress.  Here is my error:

`bash scripts/pretrain_enc_dec.sh
scripts/pretrain_enc_dec.sh: line 16: 中英混合词表: command not found
deepspeed --num_nodes 40 --num_gpus 8 --hostfile /home/thu-plm/CPM-2//src/configs/host_files/hostfile-cpm2 /home/thu-plm/CPM-2//src/pretrain_enc_dec.py --model-config /home/thu-plm/CPM-2//src/configs/model/enc_dec_xlarge_config.json --model-parallel-size 1 --batch-size 26 --enc-seq-length 512 --dec-seq-length 256 --train-iters 200000 --save /home/thu-plm/CPM-2//results/ --log-file /home/thu-plm/CPM-2//results//log.txt --data-path /home/thu-plm/CPM-2//pretrain_data/wudao_corpus --data-impl mmap --split 949,50,1 --distributed-backend nccl --lr 0.001 --no-load-optim --lr-decay-style noam --weight-decay 1e-2 --clip-grad 1.0 --warmup 0.05 --tokenizer-path --save-interval 4000 --eval-interval 2000 --eval-iters 10 --log-interval 100 --checkpoint-activations --deepspeed-activation-checkpointing --fp16 --deepspeed --deepspeed_config /home/thu-plm/CPM-2//src/configs/deepspeed/ds_cpm2.json
[2021-07-20 22:58:52,162] [WARNING] [runner.py:122:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
Traceback (most recent call last):
  File "/home/bard/miniconda3/envs/wudao/bin/deepspeed", line 6, in <module>
    main()
  File "/home/bard/miniconda3/envs/wudao/lib/python3.6/site-packages/deepspeed/launcher/runner.py", line 278, in main
    raise ValueError("Num nodes is >1 but no extra nodes available via hostfile")
ValueError: Num nodes is >1 but no extra nodes available via hostfile

`

**Comment by t1101675** [comment]
It seems that the comment "中英混合词表" in line 16 is treated as a line of code. Could you please share your training script? Or just check whether the syntax is correct.
Besides, it seems that the path to the hostfile is also incorrect. Please check whether the hostfile is put in `/home/thu-plm/CPM-2//src/configs/host_files/hostfile-cpm2`.
